/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoteRouteImport } from './routes/vote'
import { Route as TransactionSuccessRouteImport } from './routes/transaction-success'
import { Route as TransactionFailRouteImport } from './routes/transaction-fail'
import { Route as SubmissionSuccessRouteImport } from './routes/submission-success'
import { Route as SpeakersScoreboardRouteImport } from './routes/speakers-scoreboard'
import { Route as ScanBarcodeRouteImport } from './routes/scan-barcode'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailRouteImport } from './routes/payment-fail'
import { Route as BuyTicketRouteImport } from './routes/buy-ticket'
import { Route as A4RouteImport } from './routes/a4'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as VisitorSigninMagicTokenRouteImport } from './routes/visitor-signin.$magicToken'
import { Route as AdminCheckinStatsRouteImport } from './routes/admin/checkin-stats'
import { Route as AdminCheckinScanRouteImport } from './routes/admin/checkin-scan'

const VoteRoute = VoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionSuccessRoute = TransactionSuccessRouteImport.update({
  id: '/transaction-success',
  path: '/transaction-success',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionFailRoute = TransactionFailRouteImport.update({
  id: '/transaction-fail',
  path: '/transaction-fail',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionSuccessRoute = SubmissionSuccessRouteImport.update({
  id: '/submission-success',
  path: '/submission-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakersScoreboardRoute = SpeakersScoreboardRouteImport.update({
  id: '/speakers-scoreboard',
  path: '/speakers-scoreboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanBarcodeRoute = ScanBarcodeRouteImport.update({
  id: '/scan-barcode',
  path: '/scan-barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailRoute = PaymentFailRouteImport.update({
  id: '/payment-fail',
  path: '/payment-fail',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTicketRoute = BuyTicketRouteImport.update({
  id: '/buy-ticket',
  path: '/buy-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const A4Route = A4RouteImport.update({
  id: '/a4',
  path: '/a4',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorSigninMagicTokenRoute = VisitorSigninMagicTokenRouteImport.update({
  id: '/visitor-signin/$magicToken',
  path: '/visitor-signin/$magicToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinStatsRoute = AdminCheckinStatsRouteImport.update({
  id: '/admin/checkin-stats',
  path: '/admin/checkin-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckinScanRoute = AdminCheckinScanRouteImport.update({
  id: '/admin/checkin-scan',
  path: '/admin/checkin-scan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a4': typeof A4Route
  '/buy-ticket': typeof BuyTicketRoute
  '/payment-fail': typeof PaymentFailRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/scan-barcode': typeof ScanBarcodeRoute
  '/speakers-scoreboard': typeof SpeakersScoreboardRoute
  '/submission-success': typeof SubmissionSuccessRoute
  '/transaction-fail': typeof TransactionFailRoute
  '/transaction-success': typeof TransactionSuccessRoute
  '/vote': typeof VoteRoute
  '/admin/checkin-scan': typeof AdminCheckinScanRoute
  '/admin/checkin-stats': typeof AdminCheckinStatsRoute
  '/visitor-signin/$magicToken': typeof VisitorSigninMagicTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a4': typeof A4Route
  '/buy-ticket': typeof BuyTicketRoute
  '/payment-fail': typeof PaymentFailRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/scan-barcode': typeof ScanBarcodeRoute
  '/speakers-scoreboard': typeof SpeakersScoreboardRoute
  '/submission-success': typeof SubmissionSuccessRoute
  '/transaction-fail': typeof TransactionFailRoute
  '/transaction-success': typeof TransactionSuccessRoute
  '/vote': typeof VoteRoute
  '/admin/checkin-scan': typeof AdminCheckinScanRoute
  '/admin/checkin-stats': typeof AdminCheckinStatsRoute
  '/visitor-signin/$magicToken': typeof VisitorSigninMagicTokenRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a4': typeof A4Route
  '/buy-ticket': typeof BuyTicketRoute
  '/payment-fail': typeof PaymentFailRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/scan-barcode': typeof ScanBarcodeRoute
  '/speakers-scoreboard': typeof SpeakersScoreboardRoute
  '/submission-success': typeof SubmissionSuccessRoute
  '/transaction-fail': typeof TransactionFailRoute
  '/transaction-success': typeof TransactionSuccessRoute
  '/vote': typeof VoteRoute
  '/admin/checkin-scan': typeof AdminCheckinScanRoute
  '/admin/checkin-stats': typeof AdminCheckinStatsRoute
  '/visitor-signin/$magicToken': typeof VisitorSigninMagicTokenRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a4'
    | '/buy-ticket'
    | '/payment-fail'
    | '/payment-success'
    | '/scan-barcode'
    | '/speakers-scoreboard'
    | '/submission-success'
    | '/transaction-fail'
    | '/transaction-success'
    | '/vote'
    | '/admin/checkin-scan'
    | '/admin/checkin-stats'
    | '/visitor-signin/$magicToken'
    | '/admin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a4'
    | '/buy-ticket'
    | '/payment-fail'
    | '/payment-success'
    | '/scan-barcode'
    | '/speakers-scoreboard'
    | '/submission-success'
    | '/transaction-fail'
    | '/transaction-success'
    | '/vote'
    | '/admin/checkin-scan'
    | '/admin/checkin-stats'
    | '/visitor-signin/$magicToken'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a4'
    | '/buy-ticket'
    | '/payment-fail'
    | '/payment-success'
    | '/scan-barcode'
    | '/speakers-scoreboard'
    | '/submission-success'
    | '/transaction-fail'
    | '/transaction-success'
    | '/vote'
    | '/admin/checkin-scan'
    | '/admin/checkin-stats'
    | '/visitor-signin/$magicToken'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A4Route: typeof A4Route
  BuyTicketRoute: typeof BuyTicketRoute
  PaymentFailRoute: typeof PaymentFailRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ScanBarcodeRoute: typeof ScanBarcodeRoute
  SpeakersScoreboardRoute: typeof SpeakersScoreboardRoute
  SubmissionSuccessRoute: typeof SubmissionSuccessRoute
  TransactionFailRoute: typeof TransactionFailRoute
  TransactionSuccessRoute: typeof TransactionSuccessRoute
  VoteRoute: typeof VoteRoute
  AdminCheckinScanRoute: typeof AdminCheckinScanRoute
  AdminCheckinStatsRoute: typeof AdminCheckinStatsRoute
  VisitorSigninMagicTokenRoute: typeof VisitorSigninMagicTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vote': {
      id: '/vote'
      path: '/vote'
      fullPath: '/vote'
      preLoaderRoute: typeof VoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction-success': {
      id: '/transaction-success'
      path: '/transaction-success'
      fullPath: '/transaction-success'
      preLoaderRoute: typeof TransactionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction-fail': {
      id: '/transaction-fail'
      path: '/transaction-fail'
      fullPath: '/transaction-fail'
      preLoaderRoute: typeof TransactionFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submission-success': {
      id: '/submission-success'
      path: '/submission-success'
      fullPath: '/submission-success'
      preLoaderRoute: typeof SubmissionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speakers-scoreboard': {
      id: '/speakers-scoreboard'
      path: '/speakers-scoreboard'
      fullPath: '/speakers-scoreboard'
      preLoaderRoute: typeof SpeakersScoreboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan-barcode': {
      id: '/scan-barcode'
      path: '/scan-barcode'
      fullPath: '/scan-barcode'
      preLoaderRoute: typeof ScanBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-fail': {
      id: '/payment-fail'
      path: '/payment-fail'
      fullPath: '/payment-fail'
      preLoaderRoute: typeof PaymentFailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-ticket': {
      id: '/buy-ticket'
      path: '/buy-ticket'
      fullPath: '/buy-ticket'
      preLoaderRoute: typeof BuyTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a4': {
      id: '/a4'
      path: '/a4'
      fullPath: '/a4'
      preLoaderRoute: typeof A4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor-signin/$magicToken': {
      id: '/visitor-signin/$magicToken'
      path: '/visitor-signin/$magicToken'
      fullPath: '/visitor-signin/$magicToken'
      preLoaderRoute: typeof VisitorSigninMagicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin-stats': {
      id: '/admin/checkin-stats'
      path: '/admin/checkin-stats'
      fullPath: '/admin/checkin-stats'
      preLoaderRoute: typeof AdminCheckinStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/checkin-scan': {
      id: '/admin/checkin-scan'
      path: '/admin/checkin-scan'
      fullPath: '/admin/checkin-scan'
      preLoaderRoute: typeof AdminCheckinScanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A4Route: A4Route,
  BuyTicketRoute: BuyTicketRoute,
  PaymentFailRoute: PaymentFailRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ScanBarcodeRoute: ScanBarcodeRoute,
  SpeakersScoreboardRoute: SpeakersScoreboardRoute,
  SubmissionSuccessRoute: SubmissionSuccessRoute,
  TransactionFailRoute: TransactionFailRoute,
  TransactionSuccessRoute: TransactionSuccessRoute,
  VoteRoute: VoteRoute,
  AdminCheckinScanRoute: AdminCheckinScanRoute,
  AdminCheckinStatsRoute: AdminCheckinStatsRoute,
  VisitorSigninMagicTokenRoute: VisitorSigninMagicTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
