/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterSpeakerRouteImport } from './routes/register-speaker'
import { Route as IndexRouteImport } from './routes/index'

const RegisterSpeakerRoute = RegisterSpeakerRouteImport.update({
  id: '/register-speaker',
  path: '/register-speaker',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register-speaker': typeof RegisterSpeakerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register-speaker': typeof RegisterSpeakerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register-speaker': typeof RegisterSpeakerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/register-speaker'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/register-speaker'
  id: '__root__' | '/' | '/register-speaker'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterSpeakerRoute: typeof RegisterSpeakerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register-speaker': {
      id: '/register-speaker'
      path: '/register-speaker'
      fullPath: '/register-speaker'
      preLoaderRoute: typeof RegisterSpeakerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterSpeakerRoute: RegisterSpeakerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
